### ISSUE TITLE
XMLHttpRequest error

### ISSUE THREAD

**Issue by casaschi** [miscalencu/Google-Chrome-Google-Bookmarks#8]
When trying to update bookmarks, the update process does not complete and the console shows this error message:

XMLHttpRequest cannot load https://www.google.com/bookmarks?output=xml&num=10000. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://mpneoicaochhlckfkackiigepakdgapj' is therefore not allowed access.

Using ChromeOS version 51.0.2704.79

**Comment by casaschi** [comment]
It might be just a ChromeOS issue after all. Everything seems working fine with Chrome on Win, Version 51.0.2704.79 m.

**Comment by miscalencu** [comment]
Sorry, I cannot reproduce this because I do not have a ChromeOS environment to test. I made some updates, you can give it a try. But it is strange that you get that error... they should behave the same way.

Anyway, as long as I am using a unofficial API for this, I'm afraid that we have no solution for the issue.

Wait, I see that the URL has https:// instead of http://? Any idea why this happens? Could it be a local Chrome OS setting to redirect every Google request to https? This could be the explanation ...

Regards

**Comment by casaschi** [comment]
No luck, still getting this in the console
`starting ajax call ...
popup.htm#:1 XMLHttpRequest cannot load https://www.google.com/bookmarks/?output=xml&num=10000. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://mpneoicaochhlckfkackiigepakdgapj' is therefore not allowed access.
core.js:75 fail fired ...`
with the added bonus of an error popup message without any further error info.

**Comment by casaschi** [comment]
one more thought... I could not find why the chromebook changes requests to google.com from http to https, but given that is happening, then the issue might be related to the extension manifest file that requests cross-origin permission only for http://www.google.com/bookmarks/

A quick and dirty workaround could be to try adding also https://www.google.com/bookmarks/ to the permission list and see if that works. A more elegant solution would be to acknowledge the fact that google seems willing to do everything with https and change the query to retrieve the bookmarks to https in the extension code.

**Comment by miscalencu** [comment]
I just noticed that the non-authenticated user was incorrectly handled by the extension. And the URL to login was on https:// and it was triggering that error. Could this be the case on your side?

I updated the extension to show a friendly message when the user is not authenticated. Can you give it a try?

**Comment by casaschi** [comment]
Just tried v2.17, now the popup window shows the error message requesting a login, however after I login each time I try the refresh operation it fails and the console reports the same error about missing permission for the cross-origin request.

Note from this page https://developer.chrome.com/extensions/xhr
`access is granted both by host and by scheme. If an extension wants both secure and non-secure HTTP access to a given host or set of hosts, it must declare the permissions separately`
`"permissions": [
  "http://www.google.com/",
  "https://www.google.com/"
]`

**Comment by miscalencu** [comment]
I understand what you are saying, but I do not need https permissions because I am not loading the extensions through https, but http. I suspect you have something enabled that switches all http requests to https for Google.com domain.

I added the https permisssions and switched to https url (v 2.18). Let me know if it works now.

**Comment by casaschi** [comment]
it works now, thanks

I could not find more details, but it might be that some settings of the google account force the use of https on google sites. In any case, google seems intending to force more and more https on users of their services, so changing the extension to use https is probably a good idea.

**Comment by miscalencu** [comment]
Thanks! I'm glad it works now. :)
